### ISSUE TITLE
.env에 등록한 환경 변수 값 읽어오기 불가

### ISSUE THREAD

**Issue by jaeheeLee17** [jaeheeLee17/Blockchain_Transaction_Tracker#1]
현재 .env에 등록한 환경 변수 값들을 읽어오지 않는 오류가 있으니 확인 부탁드립니다.
ether price, ether count 외에도 이더리움 거래 추적 검색, 토큰 거래 추적 검색에 필요한 API들을 호출할 때 .env에 등록한 환경 변수 값을 읽어오지 못하여 환경 변수와 관련된 API 전체가 호출되지 않고 있으니 확인 즉시 수정 부탁드립니다.
![ether price, ether count 값을 가져오는 API를 호출하지 않는 오류](https://user-images.githubusercontent.com/26671655/168457981-741b7d81-5334-4e82-ad44-1ef5537b2c4e.PNG)

추가 사항 : 프론트엔드 프로젝트 폴더의 ether_price.js에서 ethCount 호출할 때는 /eth/db/ethCount를 통해서 호출하도록 변경 부탁드립니다.

**Comment by 222yujin** [comment]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/54887337/168462047-04bb46f7-333f-4f40-b589-e4ccdbed9139.png">
info - Loaded env from C:\Users\~\Blockchain_Transaction_Tracker\frontend\.env

저는 .env 파일 추가후 

1. yarn add env-cmd 
2. 프론트엔드 폴더의 package.json에서 next build를 실행했습니다

이 두가지 방법을 시도해보시고 그래도 환경변수가 안 읽히면 다른 방법을 찾아보겠습니다

**Comment by jaeheeLee17** [comment]
![next build 에러 1](https://user-images.githubusercontent.com/26671655/168465931-a2a16bcf-787a-4f09-b40d-07359181bc2b.PNG)
![next build 에러 2](https://user-images.githubusercontent.com/26671655/168465932-b543eabc-8e84-4caf-95c6-08c2a0c19a0d.PNG)
![환경 변수 읽어오기 불가](https://user-images.githubusercontent.com/26671655/168465934-5a8e7d5a-948b-44f1-99c9-b4081d34300a.PNG)
![ether price, ether count 표시 안 됨](https://user-images.githubusercontent.com/26671655/168466372-3dcd2cec-f4ae-4b04-a568-99077cf03399.PNG)
제시하신 방법대로 진행하고 애플리케이션 테스트를 했지만 여전히 환경 변수를 읽어오지 못해 API 호출이 이루어지지 않습니다. 이더리움 거래 추적 검색도 같은 이유로 실행이 안 됩니다.

**Comment by jaeheeLee17** [comment]
정상적으로 환경 변수 적용 확인했으므로 해당 이슈는 처리된 것으로 간주하고 닫겠습니다.
