### ISSUE TITLE
.env.sample에 중요 정보 노출

### ISSUE THREAD

**Issue by jaeheeLee17** [jaeheeLee17/Blockchain_Transaction_Tracker#2]
.env.sample에 외부에 노출되면 안 되는 URL 정보가 있습니다.
URL 정보는 .env 파일 생성하셔서 별도로 기록해주시고 .env.sample에는 아래 예시처럼 환경 변수 이름만 표시되도록 수정해주시기 바랍니다.

ex) NEXT_PUBLIC_API_ROOT=NEXT_PUBLIC_API_ROOT

**Comment by 222yujin** [comment]
수정 완료 했습니다

**Comment by jaeheeLee17** [comment]
넵 확인했습니다.
