### ISSUE TITLE
/eth/network/txlistchain API 호출 오류

### ISSUE THREAD

**Issue by jaeheeLee17** [jaeheeLee17/Blockchain_Transaction_Tracker#3]
![txlistchain 목록 불러오는 API가 호출되지 않는 오류](https://user-images.githubusercontent.com/26671655/168472321-5e828d06-7404-4d79-ae79-3de4ffa1bde4.PNG) 
![no data 출력](https://user-images.githubusercontent.com/26671655/168472400-c7824dd5-cd28-40ca-a1ea-a63fb826938a.PNG)
cryptocurrency dashboard에서 이전에 검색한 적이 없던 지갑 주소를 입력하여 검색하면 지갑 주소 검색 기록을 DB에 저장하고 blockchain network에서 사용자가 검색한 지갑 주소 관련 이더리움 거래 추적 내역이 담긴 목록을 DB에 저장한 후 DB에서 가져와서 그래프로 화면에 출력해야 하지만 /eth/network/txlistchain을 호출하지 않아 이더리움 거래 추적 내역을 DB에 저장하지 않아서 이후에 같은 주소로 검색 시 no data로만 출력됩니다.

**Comment by 222yujin** [comment]
확인해보니 환경변수 설정하면서 엔드포인트에서 '/'가 하나 빠진 오타로 해당 api의 호출이 제대로 이루어지지 않았던 것 같습니다
오타 수정해서 push 하겠습니다

**Comment by jaeheeLee17** [comment]
넵 확인했고 몇몇 API 경로에 오타가 있어 이 부분은 제가 수정해서 다시 front_feature에 push했습니다.
