### ISSUE TITLE
이더리움 거래 추적 API 호출 후 데이터를 DB에 저장했으나 화면에 no data 메시지 호출

### ISSUE THREAD

**Issue by jaeheeLee17** [jaeheeLee17/Blockchain_Transaction_Tracker#4]
![트랜젝션 거래 추적 API 호출](https://user-images.githubusercontent.com/26671655/168760391-fc2520d1-19ec-4013-afa5-dbcb412d069b.PNG)
![DB에 저장된 트랜젝션 거래 추적 내역](https://user-images.githubusercontent.com/26671655/168760434-d33bf151-a289-429b-8ca8-a2183a5d2023.PNG)
![DB에 데이터가 있음에도 no data 출력](https://user-images.githubusercontent.com/26671655/168760445-0bd848fd-3f04-4fe6-96b8-03595462f516.PNG)
이더리움 거래 추적 API 호출 후 거래 추적 내역을 DB에 저장한 것이 확인됐으나 1번에 그래프로 표현하지 못하고 no data 메시지를 띄웁니다. 이후 같은 주소로 1번 더 검색하면 DB에서 거래 추적 내역을 캐싱하여 그래프로 표현하는 것이 확인됩니다.
해당 이슈 검토해주시고 가능하다면 이더리움 거래 추적 API 호출 후 이더리움 거래 추적 내역을 그래프로 표현하는 것까지 1번에 이뤄질 수 있도록 수정해주시면 감사하겠습니다.

**Comment by 222yujin** [comment]
거래 추적내역이 db에 저장되는 속도가 느려, 완전히 저장되지 않은 상태에서 조회 api가 실행되어 발생한 오류로 파악됩니다.
조회 api를 호출하기전에 3초 정도 delay를 줘서 해결했습니다.

**Comment by jaeheeLee17** [comment]
넵 확인했습니다
